### ISSUE TITLE
README Typo

### ISSUE THREAD

**Issue by CrazyPyroEagle** [bucket3432/programmer-animeme-subs#1]
> * **r/ProgrammerAnimemes post**: "[Dependencies](https://www.reddit.com/r/ProgrammerAnimemes/comments/ew6k2n/dependencies/)" (posted 2019-01-30)

Says "posted 2019-01-30" when it should say "posted 2020-01-30".

**Comment by bucket3432** [comment]
Thanks. I guess my fingers are still not quite there yet.
